CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE IF NOT EXISTS public."user"
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL,
    google_refresh_token VARCHAR NOT NULL
)